#!/usr/bin/env python3
"""Generate and verify the APS-038 center-preserving voice gain table."""

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "title_voice_gain.inc"
GAIN_NUMERATOR = 5
GAIN_DENOMINATOR = 4
ASSETS = (
    ("title", ROOT / "assets" / "voice" / "title-start.adpcm",
     ROOT / "assets" / "voice" / "title-start.json"),
    ("game-over", ROOT / "assets" / "voice" / "game-over.adpcm",
     ROOT / "assets" / "voice" / "game-over.json"),
)


def signed_sample(dac_byte):
    return dac_byte if dac_byte < 0x80 else dac_byte - 0x100


def gain_signed_sample(sample):
    """Apply 5/4 gain, truncating magnitude toward zero, then saturating."""
    magnitude = abs(sample)
    scaled = (magnitude * GAIN_NUMERATOR) // GAIN_DENOMINATOR
    if sample < 0:
        return -min(scaled, 128)
    return min(scaled, 127)


def gain_dac_byte(dac_byte):
    return gain_signed_sample(signed_sample(dac_byte)) & 0xFF


def gain_would_clamp(dac_byte):
    sample = signed_sample(dac_byte)
    scaled = (abs(sample) * GAIN_NUMERATOR) // GAIN_DENOMINATOR
    return scaled > (128 if sample < 0 else 127)


def gain_table():
    return [gain_dac_byte(value) for value in range(256)]


def table_text():
    values = gain_table()
    rows = [
        "        .byte   "
        + ",".join(f"${value:02x}" for value in values[offset : offset + 16])
        for offset in range(0, len(values), 16)
    ]
    return (
        "; Generated by scripts/generate-title-voice-gain.py.\n"
        "; signed magnitude floor(5/4), then clamp to -128..127.\n"
        "voice_gain_table:\n"
        + "\n".join(rows)
        + "\n"
    )


def load_codec_tables():
    generator_path = ROOT / "scripts" / "generate-title-voice.py"
    spec = importlib.util.spec_from_file_location("title_voice_generator", generator_path)
    generator = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(generator)
    return generator.STEP_TABLE, generator.INDEX_DELTA


def decode_asset(path, sample_count):
    steps, index_delta = load_codec_tables()
    packed = path.read_bytes()
    predictor = 0
    step_index = 0
    output = []
    for sample_index in range(sample_count):
        byte = packed[sample_index // 2]
        code = byte & 0x0F if sample_index % 2 == 0 else byte >> 4
        step = steps[step_index]
        difference = step >> 3
        if code & 1:
            difference += step >> 2
        if code & 2:
            difference += step >> 1
        if code & 4:
            difference += step
        predictor += -difference if code & 8 else difference
        predictor = max(-32768, min(32767, predictor))
        step_index += index_delta[code & 7]
        step_index = max(0, min(88, step_index))
        output.append((predictor >> 8) & 0xFF)
    return output


def analyze_asset(name, asset_path, metadata_path):
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    sample_count = metadata["sample_count"]
    decoded = decode_asset(asset_path, sample_count)
    gained = [gain_dac_byte(value) for value in decoded]
    before = [signed_sample(value) for value in decoded]
    after = [signed_sample(value) for value in gained]
    clamp_count = sum(gain_would_clamp(value) for value in decoded)
    silent_tail = 0
    for value in reversed(decoded):
        if value != 0:
            break
        silent_tail += 1
    digest = hashlib.sha256(asset_path.read_bytes()).hexdigest()
    print(
        f"voice gain {name}: samples={sample_count} sha256={digest} "
        f"before_min={min(before)} before_max={max(before)} "
        f"before_peak={max(abs(min(before)), abs(max(before)))} "
        f"after_min={min(after)} after_max={max(after)} "
        f"after_peak={max(abs(min(after)), abs(max(after)))} "
        f"center_before={before.count(0)} center_after={after.count(0)} "
        f"clamp={clamp_count} clamp_ratio={clamp_count / sample_count:.6%} "
        f"silent_tail={silent_tail}"
    )


def verify():
    expected = table_text()
    if not OUTPUT.is_file():
        raise SystemExit(f"missing generated voice gain table: {OUTPUT}")
    actual = OUTPUT.read_text(encoding="ascii")
    if actual != expected:
        raise SystemExit(
            "voice gain table mismatch; run "
            "scripts/generate-title-voice-gain.py generate"
        )
    table = gain_table()
    if table[0x00] != 0x00 or table[0x80] != 0x80 or table[0x7F] != 0x7F:
        raise SystemExit("voice gain center or clamp endpoints are invalid")
    print(f"voice gain table OK: entries={len(table)} bytes={OUTPUT.stat().st_size}")
    for asset in ASSETS:
        analyze_asset(*asset)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("generate", "verify", "analyze"))
    args = parser.parse_args()
    if args.command == "generate":
        OUTPUT.write_text(table_text(), encoding="ascii")
        print(f"generated: {OUTPUT} ({OUTPUT.stat().st_size} bytes)")
    elif args.command == "verify":
        verify()
    else:
        for asset in ASSETS:
            analyze_asset(*asset)


if __name__ == "__main__":
    main()
