#!/usr/bin/env python3
"""Generate 65SC02 IMA difference tables used by the APS-032 IRQ."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "title_voice_delta.inc"
STEPS = (
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31,
    34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118,
    130, 143, 157, 173, 190, 209, 230, 253, 279, 307, 337, 371,
    408, 449, 494, 544, 598, 658, 724, 796, 876, 963, 1060, 1166,
    1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024,
    3327, 3660, 4026, 4428, 4871, 5358, 5894, 6484, 7132, 7845,
    8630, 9493, 10442, 11487, 12635, 13899, 15289, 16818, 18500,
    20350, 22385, 24623, 27086, 29794, 32767,
)


def difference(step, magnitude):
    value = step >> 3
    if magnitude & 1:
        value += step >> 2
    if magnitude & 2:
        value += step >> 1
    if magnitude & 4:
        value += step
    return value


def rows(values):
    return "\n".join(
        "        .byte   " + ",".join(f"${value:02x}" for value in values[i : i + 16])
        for i in range(0, len(values), 16)
    )


def main():
    output = ["; Generated by scripts/generate-title-voice-delta.py.\n"]
    for magnitude in range(8):
        values = [difference(step, magnitude) for step in STEPS]
        output.append(f"difference_{magnitude}_low:\n")
        output.append(rows([value & 0xFF for value in values]) + "\n")
        output.append(f"difference_{magnitude}_high:\n")
        output.append(rows([value >> 8 for value in values]) + "\n")
    OUTPUT.write_text("".join(output), encoding="ascii")
    print(f"generated: {OUTPUT} ({OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
