#ifndef GAME_OVER_VOICE_DATA_H
#define GAME_OVER_VOICE_DATA_H

#define GAME_OVER_VOICE_SAMPLE_RATE 8000u
#define GAME_OVER_VOICE_SAMPLE_COUNT 11691u
#define GAME_OVER_VOICE_ADPCM_BYTE_COUNT 5846u
#define GAME_OVER_VOICE_INITIAL_PREDICTOR 0
#define GAME_OVER_VOICE_INITIAL_STEP_INDEX 0u

#endif
