#ifndef STATIC_LAYER_DATA_H
#define STATIC_LAYER_DATA_H

#include <stddef.h>

#define STATIC_LAYER_CLEAR_WIDTH 1
#define STATIC_LAYER_CLEAR_HEIGHT 1
#define STATIC_LAYER_CLEAR_Y_OFFSET 0
#define STATIC_LAYER_CLEAR_BPP 1
extern const unsigned char static_layer_clear_data[];

#define STATIC_LAYER_PLANET_Y_OFFSET 0
#define STATIC_LAYER_MOUNTAIN_Y_OFFSET 58
#define STATIC_LAYER_MID_CLOUD_Y_OFFSET 18
#define STATIC_LAYER_NEAR_CLOUD_Y_OFFSET 68
#define STATIC_LAYER_CAVE_WALL_Y_OFFSET 24
#define STATIC_LAYER_CAVE_ROCK_Y_OFFSET 10
#define STATIC_LAYER_CAVE_NEAR_Y_OFFSET 15
#define STATIC_LAYER_SPACE_FAR_STAR_Y_OFFSET 0
#define STATIC_LAYER_NEAR_STAR_Y_OFFSET 0

#define STATIC_LAYER_FONT_COUNT 32
#define STATIC_LAYER_FONT_WIDTH 5
#define STATIC_LAYER_FONT_HEIGHT 7
extern const unsigned char static_layer_font_bits[];
#define STATIC_LAYER_NEAR_STAR_COUNT 7
#define STATIC_LAYER_FAR_STAR_COUNT 10

#endif
