#ifndef TITLE_VOICE_DATA_H
#define TITLE_VOICE_DATA_H

#define TITLE_VOICE_SAMPLE_RATE 8000u
#define TITLE_VOICE_SAMPLE_COUNT 17408u
#define TITLE_VOICE_ADPCM_BYTE_COUNT 8704u
#define TITLE_VOICE_INITIAL_PREDICTOR 0
#define TITLE_VOICE_INITIAL_STEP_INDEX 0u

#endif
