#include <6502.h>
#include <joystick.h>
#include <lynx.h>
#include <tgi.h>

#ifdef CADENCE_PROBE
#include "cadence_probe.h"
#include "scb_split_probe.h"
#endif
#include "game.h"
#include "game_timing.h"
#include "sprite_data.h"
#include "static_layer.h"
#include "title_voice.h"
#include "version.h"
#ifdef CADENCE_PROBE
#include "cadence_probe.h"
#endif

#define GAME_COLOR_BLACK 0u
#define GAME_COLOR_WHITE 15u
#define GAME_COLOR_PLANET_BODY 1u
#define GAME_COLOR_PLANET_DETAIL 3u
#define GAME_COLOR_FAR_STAR 3u
#define GAME_COLOR_NEAR_STAR 4u
#define GAME_COLOR_DANGER 6u
#define GAME_COLOR_PLAYER_GLOW 7u
#define GAME_COLOR_PLAYER_HULL 8u
#define GAME_COLOR_PLAYER_DEEP 9u
#define GAME_COLOR_ENEMY_HULL 10u
#define GAME_COLOR_ENEMY_DARK 11u
#define GAME_COLOR_GLOW_YELLOW 12u
#define GAME_COLOR_MINERAL_VIOLET 13u
#define GAME_COLOR_MINERAL_TEAL 14u
#define GAME_COLOR_BULLET GAME_COLOR_PLAYER_GLOW
#define GAME_COLOR_ENEMY_BULLET GAME_COLOR_DANGER
#define GAME_COLOR_POWER_ITEM GAME_COLOR_GLOW_YELLOW
#define GAME_COLOR_EXPLOSION GAME_COLOR_DANGER
#define GAME_COLOR_SKY 0u
#define GAME_COLOR_MOUNTAIN 1u
#define GAME_COLOR_MID_CLOUD 3u
#define GAME_COLOR_NEAR_CLOUD 4u
#define GAME_COLOR_CAVE_WALL 0u
#define GAME_COLOR_CAVE_SHADOW 1u
#define GAME_COLOR_CAVE_ROCK 3u
#define GAME_COLOR_CAVE_NEAR 4u
#define GAME_COLOR_ENVIRONMENT_BODY GAME_COLOR_MINERAL_VIOLET
#define GAME_COLOR_ENVIRONMENT_DETAIL GAME_COLOR_MINERAL_TEAL
#define GAME_COLOR_WIND_WARNING 6u
#define GAME_COLOR_WIND_ACTIVE GAME_COLOR_MINERAL_TEAL
#define SCORE_DIGITS 5u
#define VOICE_CREDIT_ASCII_X 12u
#define VOICE_CREDIT_SUFFIX_X 116u
#define VOICE_CREDIT_Y 82u
#ifdef APS056_DIAGNOSTIC
#define LYNX_OPTION_BUTTONS (*(volatile unsigned char*)0xfcb0u)
#define LYNX_OPT1_MASK 0x04u
#define LYNX_OPT2_MASK 0x08u
unsigned char aps056_active_bullet_count;
#endif

/* MIKEY audio channel register blocks (include/_mikey.h layout): eight
 * registers per channel starting at 0xFD20 (channel A), 0xFD28
 * (channel B) and 0xFD30 (channel C, added APS-023 for the bassline).
 * All three channels share the same in-block offsets, so the backend
 * addresses them as base pointer plus offset (APS-021). */
#define SOUND_CHANNEL_A ((volatile unsigned char*)0xfd20u)
#define SOUND_CHANNEL_B ((volatile unsigned char*)0xfd28u)
#define SOUND_CHANNEL_C ((volatile unsigned char*)0xfd30u)
#define SOUND_REG_VOL 0u
#define SOUND_REG_FEEDBACK 1u
#define SOUND_REG_OUTPUT 2u
#define SOUND_REG_SHIFT_LOW 3u
#define SOUND_REG_RELOAD 4u
#define SOUND_REG_CONTROL_A 5u
#define SOUND_REG_CONTROL_B 7u
#define SOUND_MASTER_STEREO (*(volatile unsigned char*)0xfd50u)
#define SOUND_TIMER_ENABLE 0x18u
/* Bit 5 of the control register switches the LFSR output from an
 * instant +/-volume flip (sharp square wave, the "BEEP" timbre) to an
 * accumulator (acc += +/-volume per underflow, clamped to -128..127).
 * APS-026 applied it to every channel while keeping the APS-013 LFSR
 * patterns; those patterns emit unequal counts of 1s and 0s per cycle
 * (e.g. tone: 3 ones vs 4 zeros every 7 ticks), so the accumulator
 * drifted to the -128/+127 rail within milliseconds and pinned there,
 * degenerating the output into a low clipped drone (the reported
 * "buzz"). APS-027 therefore makes integrate a per-wave property
 * (SoundWaveRegister.integrate): only waves whose LFSR cycle is
 * DC-balanced (equal 1s and 0s -- see the table below) may set it,
 * which turns them into clean triangle waves instead. */
#define SOUND_INTEGRATE_MODE 0x20u

typedef struct SoundPitchRegister {
    unsigned char reload;
    unsigned char prescaler;
} SoundPitchRegister;

typedef struct SoundWaveRegister {
    unsigned char feedback;
    unsigned char shift_low;
    unsigned char control_b;
    /* 0 or SOUND_INTEGRATE_MODE, ORed into control A (APS-027). Only
     * safe on waves whose LFSR cycle is DC-balanced; see the table
     * comment below. */
    unsigned char integrate;
} SoundWaveRegister;

typedef struct SoundHardwareState {
    unsigned char active;
    unsigned char note;
    unsigned char volume;
    unsigned char wave;
} SoundHardwareState;

/* APS-028 retune, generated by scripts/gen-pitch-tables.py -- edit and
 * rerun that script instead of hand-editing these values.
 *
 * A MIKEY channel does not emit one waveform edge per timer underflow:
 * each underflow shifts the LFSR once and the audible waveform only
 * repeats after a full LFSR cycle, so the perceived fundamental is
 * f_underflow / lfsr_cycle_len. Furnace (src/engine/platform/lynx.cpp,
 * DUTY_DIVIDERS[] + "tuned" mode) divides the target frequency by
 * exactly this cycle length before programming BACKUP/CONTROL. The
 * previous single table (APS-013) was never divided by the real cycle
 * lengths (TONE 6, METALLIC 63, NOISE 6, PULSE 8), so every voice
 * sounded 3x-31x below its intended pitch: the whole mix sat in the
 * 62-220 Hz band, which is the persistent low "buzz" reported since
 * APS-020. It also used uniform ~1.075 ratio steps instead of the
 * C-major diatonic scale that mml2c's note ids 1..16 encode
 * ((octave-1)*7 + degree), so melodies additionally played with
 * compressed, out-of-tune intervals.
 *
 * These tables map note id n to its equal-tempered diatonic frequency
 * (id 1 = C4 ... id 16 = D6, A4 = 440 Hz) multiplied by the wave's
 * LFSR cycle length; timer period = (reload+1) * 2^prescaler us. */
static const SoundPitchRegister sound_pitch_registers[
    SOUND_WAVE_COUNT][SOUND_NOTE_COUNT] = {
    /* TONE: LFSR cycle 6, worst pitch error 0.21% */
    {
    { 0x9eu, 2u }, { 0x8du, 2u }, { 0xfcu, 1u }, { 0xeeu, 1u },
    { 0xd4u, 1u }, { 0xbcu, 1u }, { 0xa8u, 1u }, { 0x9eu, 1u },
    { 0x8du, 1u }, { 0xfcu, 0u }, { 0xeeu, 0u }, { 0xd4u, 0u },
    { 0xbcu, 0u }, { 0xa8u, 0u }, { 0x9eu, 0u }, { 0x8du, 0u }
    },
    /* METALLIC: LFSR cycle 63, worst pitch error 3.60% */
    {
    { 0x3cu, 0u }, { 0x35u, 0u }, { 0x2fu, 0u }, { 0x2cu, 0u },
    { 0x27u, 0u }, { 0x23u, 0u }, { 0x1fu, 0u }, { 0x1du, 0u },
    { 0x1au, 0u }, { 0x17u, 0u }, { 0x16u, 0u }, { 0x13u, 0u },
    { 0x11u, 0u }, { 0x0fu, 0u }, { 0x0eu, 0u }, { 0x0du, 0u }
    },
    /* NOISE: LFSR cycle 6, worst pitch error 0.21% */
    {
    { 0x9eu, 2u }, { 0x8du, 2u }, { 0xfcu, 1u }, { 0xeeu, 1u },
    { 0xd4u, 1u }, { 0xbcu, 1u }, { 0xa8u, 1u }, { 0x9eu, 1u },
    { 0x8du, 1u }, { 0xfcu, 0u }, { 0xeeu, 0u }, { 0xd4u, 0u },
    { 0xbcu, 0u }, { 0xa8u, 0u }, { 0x9eu, 0u }, { 0x8du, 0u }
    },
    /* PULSE: LFSR cycle 8, worst pitch error 0.39% */
    {
    { 0xeeu, 1u }, { 0xd4u, 1u }, { 0xbdu, 1u }, { 0xb2u, 1u },
    { 0x9eu, 1u }, { 0x8du, 1u }, { 0xfcu, 0u }, { 0xeeu, 0u },
    { 0xd4u, 0u }, { 0xbdu, 0u }, { 0xb2u, 0u }, { 0x9eu, 0u },
    { 0x8du, 0u }, { 0x7eu, 0u }, { 0x76u, 0u }, { 0x69u, 0u }
    }
};

/* APS-027 retune. MIKEY's LFSR inserts XNOR(selected taps) each timer
 * underflow; a single tap k with the low k+1 shift bits seeded uniform
 * degenerates into a twisted ring counter emitting k+1 ones then k+1
 * zeros forever (verified against Gearlynx AdvanceLFSR by
 * scripts/sim-mikey-lfsr.py). Such a cycle is DC-balanced, so with the
 * integrate bit set the channel outputs a clean triangle wave of
 * amplitude (k+1)*volume with zero net drift -- the volume envelope
 * (APS-026) then audibly scales the triangle instead of vanishing into
 * the clamp rail.
 *   TONE:  tap 2, seed 0b111  -> 111000 cycle, triangle period 6
 *          (previous square cycle period was 7: uniform ~+2.7
 *          semitone transposition, melody intervals unchanged)
 *   PULSE: tap 3, seed 0b1111 -> 11110000 cycle, triangle period 8
 *          (previous cycle period was 9: uniform ~+2 semitones)
 * METALLIC and NOISE keep their APS-013 pseudo-random patterns and
 * stay in non-integrate mode: their cycles are imbalanced (-1/63 and
 * +4/6 per period), so integrating them recreates the rail-pinned
 * drone, and their harsh character is intentional for SFX accents. */
static const SoundWaveRegister sound_wave_registers[SOUND_WAVE_COUNT] = {
    { 0x04u, 0x07u, 0u, SOUND_INTEGRATE_MODE },
    { 0x36u, 0x5au, 0u, 0u },
    { 0x1fu, 0x7fu, 0u, 0u },
    { 0x08u, 0x0fu, 0u, SOUND_INTEGRATE_MODE }
};

static SoundHardwareState sound_hardware_bgm;
static SoundHardwareState sound_hardware_bgm_bass;
static SoundHardwareState sound_hardware_sfx;
GameState game;
GameEnemy game_enemies[GAME_MAX_ENEMIES];

void game_display_request(void);
void game_display_sync_complete(void);
static unsigned char active_palette_stage;

/* Fixed wiring of one logical sound output to one MIKEY channel. The
 * map rows keep the historical register write order (A, C, B). Adding
 * a voice (channel D at 0xfd38) is one more row here plus its
 * SoundOutput in SoundState -- init and the main loop iterate the map
 * instead of naming each channel. */
typedef struct SoundChannelMap {
    volatile unsigned char* mikey_channel;
    SoundHardwareState* hardware;
    const SoundOutput* output;
} SoundChannelMap;

#define SOUND_CHANNEL_MAP_COUNT 3u

static const SoundChannelMap sound_channel_map[SOUND_CHANNEL_MAP_COUNT] = {
    { SOUND_CHANNEL_A, &sound_hardware_bgm, &game.sound.output_bgm },
    { SOUND_CHANNEL_C, &sound_hardware_bgm_bass,
        &game.sound.output_bgm_bass },
    { SOUND_CHANNEL_B, &sound_hardware_sfx, &game.sound.output_sfx }
};

static const unsigned char explosion_masks[GAME_EXPLOSION_STAGES][8] = {
    { 0x00u, 0x00u, 0x18u, 0x3cu, 0x3cu, 0x18u, 0x00u, 0x00u },
    { 0x00u, 0x24u, 0x18u, 0x7eu, 0x7eu, 0x18u, 0x24u, 0x00u },
    { 0x81u, 0x24u, 0x5au, 0x3cu, 0x3cu, 0x5au, 0x24u, 0x81u },
    { 0x42u, 0x81u, 0x24u, 0x00u, 0x00u, 0x24u, 0x81u, 0x42u }
};

/* APS-053 Phase 3R: Suzy packed-bitmap (1bpp, PACKED encoding, see
 * scripts/generate-static-layer.py encode_packed) replacements for the
 * pre-3R raw 8-bit-row masks these five shapes used with draw_mask/
 * draw_rect. Each is a single solid color (the movable_scb_* header's
 * penpal[0] supplies the real 0-15 palette value, set once at chain-init
 * time -- see the header initializers below), so no penpal table is
 * authored here -- unlike the 13 preview-authored sprites,
 * these are not part of the bpp gate (verify-phase-3r-sprite-bpp-gate.py)
 * and were re-encoded by hand from the removed mask arrays with the same
 * encode_packed() call used to generate them; see .briefs/APS-053/v036.md. */
static const unsigned char power_item_shape[13] = {
    0x03u, 0x93u, 0x00u, 0x03u, 0x1cu, 0x00u, 0x03u, 0x1cu, 0x00u, 0x03u,
    0x93u, 0x00u, 0x00u
};

static const unsigned char asteroid_shape_0[25] = {
    0x03u, 0xa0u, 0xc0u, 0x03u, 0x80u, 0x90u, 0x03u, 0x34u, 0x00u, 0x03u,
    0xbeu, 0xd8u, 0x03u, 0x3cu, 0x00u, 0x03u, 0x80u, 0xb0u, 0x03u, 0x88u,
    0x38u, 0x03u, 0xa0u, 0xc0u, 0x00u
};

static const unsigned char asteroid_shape_1[26] = {
    0x03u, 0xa8u, 0xe0u, 0x03u, 0x80u, 0xb0u, 0x03u, 0x3cu, 0x00u, 0x04u,
    0x8cu, 0x3cu, 0x50u, 0x03u, 0x80u, 0xd0u, 0x03u, 0x88u, 0x48u, 0x03u,
    0xa8u, 0xe0u, 0x03u, 0x1au, 0x10u, 0x00u
};

static const unsigned char* const asteroid_shapes[2] = {
    asteroid_shape_0, asteroid_shape_1
};

static const unsigned char falling_rock_shape_0[25] = {
    0x03u, 0xa0u, 0xc0u, 0x03u, 0x88u, 0x38u, 0x03u, 0x80u, 0xb0u, 0x03u,
    0x3cu, 0x00u, 0x03u, 0xbeu, 0xd8u, 0x03u, 0x80u, 0xb0u, 0x03u, 0x88u,
    0x38u, 0x03u, 0xa0u, 0xc0u, 0x00u
};

static const unsigned char falling_rock_shape_1[26] = {
    0x03u, 0x1au, 0x38u, 0x03u, 0x88u, 0x48u, 0x03u, 0x80u, 0xd0u, 0x03u,
    0x3cu, 0x00u, 0x04u, 0x8cu, 0x3cu, 0x50u, 0x03u, 0x80u, 0xb0u, 0x03u,
    0xa1u, 0xc0u, 0x03u, 0x98u, 0x80u, 0x00u
};

static const unsigned char* const falling_rock_shapes[2] = {
    falling_rock_shape_0, falling_rock_shape_1
};

static const unsigned char player_bullet_shape[7] = {
    0x03u, 0x97u, 0x00u, 0x03u, 0x97u, 0x00u, 0x00u
};

static const unsigned char enemy_bullet_shape[7] = {
    0x03u, 0x97u, 0x00u, 0x03u, 0x8au, 0x00u, 0x00u
};

static void sound_backend_silence_channel(volatile unsigned char* channel,
    SoundHardwareState* hardware, unsigned char write_registers)
{
    if (write_registers != 0u) {
        channel[SOUND_REG_VOL] = 0u;
        channel[SOUND_REG_CONTROL_A] = 0u;
        /* APS-027: also clear the output accumulator. In integrate
         * mode it holds the last accumulated level, and a disabled
         * channel keeps mixing its output register as a DC offset. */
        channel[SOUND_REG_OUTPUT] = 0u;
    }
    hardware->active = 0u;
    hardware->note = SOUND_NOTE_REST;
    hardware->volume = 0u;
    hardware->wave = SOUND_WAVE_TONE;
}

static void sound_backend_init(void)
{
    unsigned char i;

    SOUND_MASTER_STEREO = 0u;
    for (i = 0u; i < SOUND_CHANNEL_MAP_COUNT; ++i) {
        sound_backend_silence_channel(sound_channel_map[i].mikey_channel,
            sound_channel_map[i].hardware, 1u);
    }
}

/* Applies one logical channel output to one MIKEY channel. Shared by
 * every sound_channel_map row since APS-021: the previous per-channel
 * duplicates used the same register offsets and the same APS-013
 * write ordering (control=0, shift-low, control-B, feedback, volume,
 * reload, control=prescaler|enable; volume-only rewrite when just the
 * volume changes), which this helper preserves verbatim. */
static void sound_backend_apply(volatile unsigned char* channel,
    SoundHardwareState* hardware, const SoundOutput* output)
{
    const SoundPitchRegister* pitch;
    const SoundWaveRegister* wave;
    unsigned char hardware_volume;

    if (output->active == 0u || output->note == SOUND_NOTE_REST ||
        output->note > SOUND_NOTE_COUNT ||
        output->wave >= SOUND_WAVE_COUNT) {
        sound_backend_silence_channel(channel, hardware, hardware->active);
        return;
    }

    /* APS-028: the pitch registers depend on the wave's LFSR cycle
     * length, so the lookup is per wave (see the table comment). */
    pitch = &sound_pitch_registers[output->wave][output->note - 1u];
    wave = &sound_wave_registers[output->wave];
    hardware_volume = sound_hardware_volume(output->volume);
    if (hardware->active == 0u ||
        output->note != hardware->note ||
        output->wave != hardware->wave) {
        channel[SOUND_REG_CONTROL_A] = 0u;
        channel[SOUND_REG_SHIFT_LOW] = wave->shift_low;
        channel[SOUND_REG_CONTROL_B] = wave->control_b;
        channel[SOUND_REG_FEEDBACK] = wave->feedback;
        /* APS-027: restart the integrate accumulator from zero so a
         * level carried over from the previous note/SFX cannot push
         * the new note's triangle into the +/-128 clamp. */
        channel[SOUND_REG_OUTPUT] = 0u;
        channel[SOUND_REG_VOL] = hardware_volume;
        channel[SOUND_REG_RELOAD] = pitch->reload;
        channel[SOUND_REG_CONTROL_A] = (unsigned char)(pitch->prescaler |
            SOUND_TIMER_ENABLE | wave->integrate);
    } else if (hardware_volume != hardware->volume) {
        channel[SOUND_REG_VOL] = hardware_volume;
    }
    hardware->active = 1u;
    hardware->note = output->note;
    hardware->volume = hardware_volume;
    hardware->wave = output->wave;
}

/* Pushes every logical output onto its mapped MIKEY channel; called
 * once per draw frame from the main loop. */
static void sound_backend_apply_all(void)
{
    const SoundChannelMap* map;
    unsigned char i;

    for (i = 0u; i < SOUND_CHANNEL_MAP_COUNT; ++i) {
        map = &sound_channel_map[i];
        sound_backend_apply(map->mikey_channel, map->hardware, map->output);
    }
}

unsigned char game_input_poll(void)
{
    unsigned char joy;
    unsigned char input;

    joy = joy_read(JOY_1);
    input = 0u;
    if ((joy & JOY_UP_MASK) != 0u) {
        input |= GAME_INPUT_UP;
    }
    if ((joy & JOY_DOWN_MASK) != 0u) {
        input |= GAME_INPUT_DOWN;
    }
    if ((joy & JOY_LEFT_MASK) != 0u) {
        input |= GAME_INPUT_LEFT;
    }
    if ((joy & JOY_RIGHT_MASK) != 0u) {
        input |= GAME_INPUT_RIGHT;
    }
    if ((joy & (JOY_BTN_1_MASK | JOY_BTN_2_MASK)) != 0u) {
        input |= GAME_INPUT_FIRE;
    }
#ifdef APS056_DIAGNOSTIC
    if ((LYNX_OPTION_BUTTONS & LYNX_OPT1_MASK) != 0u) {
        input |= GAME_INPUT_DIAGNOSTIC_OPT1;
    }
    if ((LYNX_OPTION_BUTTONS & LYNX_OPT2_MASK) != 0u) {
        input |= GAME_INPUT_DIAGNOSTIC_OPT2;
    }
#endif
    return input;
}

/* APS-053 Phase 3R: the player death explosion FX is not one of the 41
 * movable objects converted to Suzy SCBs (see the movable_scb_env_header
 * comment below) -- it stays on this row-mask/tgi_bar path. */
static void draw_mask(int x, int y,
    unsigned char width, unsigned char height,
    const unsigned char* rows, unsigned char color)
{
    unsigned char row;
    unsigned char column;
    unsigned char run_start;
    unsigned char mask;
    int draw_y;
    int x0;
    int x1;

    tgi_setcolor(color);
    for (row = 0u; row < height; ++row) {
        draw_y = y + row;
        if (draw_y < 0 || draw_y >= (int)GAME_SCREEN_HEIGHT) {
            continue;
        }
        column = 0u;
        while (column < width) {
            mask = (unsigned char)(0x80u >> column);
            if ((rows[row] & mask) == 0u) {
                ++column;
                continue;
            }
            run_start = column;
            do {
                ++column;
                if (column == width) {
                    break;
                }
                mask = (unsigned char)(0x80u >> column);
            } while ((rows[row] & mask) != 0u);

            x0 = x + run_start;
            x1 = x + column - 1u;
            if (x1 >= 0 && x0 < (int)GAME_SCREEN_WIDTH) {
                if (x0 < 0) {
                    x0 = 0;
                }
                if (x1 >= (int)GAME_SCREEN_WIDTH) {
                    x1 = (int)GAME_SCREEN_WIDTH - 1;
                }
                tgi_bar((unsigned int)x0, (unsigned int)draw_y,
                    (unsigned int)x1, (unsigned int)draw_y);
            }
        }
    }
}

/* APS-053 Phase 3R2 (v045, replacing the v036 dynamic-append design):
 * movable objects (player/enemy/boss/power item/bullets/environment
 * hazards) are drawn as one static Suzy SCB chain, built once at startup
 * (movable_scb_init) and linked forever after. Every frame only mutates
 * SPRCTL1's SKIP bit plus hpos/vpos/data in place -- no SCB is ever
 * appended, sized, or re-linked at runtime. Suzy is fixed at 1x scale
 * project-wide (APS-050), so SPRCTL1's HSIZE/VSIZE reload is never needed
 * here: the hardware HSIZE/VSIZE registers already hold 0x0100 (1x) left
 * over from the last SCB in the background chain (src/static_layer.c
 * reset_scb always writes 0x0100 except for the one full-screen clear
 * sprite, which static_layer_draw() always submits first in that same
 * chain, before this one runs). SCB_RENONE/SCB_RENONE_PAL (_suzy.h,
 * 11B/19B) are used instead of the 23B SCB_REHV_PAL the background layer
 * uses, dropping the HSIZE/VSIZE/stretch/tilt fields this chain never
 * reloads.
 *
 * Chain layout (fixed link order == current draw order, see
 * .briefs/APS-053/v044.md "chain construction"):
 *   env header (19B, own penpal) -> env[0..GAME_MAX_ENVIRONMENT_OBJECTS-1]
 *     (11B each, REUSEPAL)
 *   -> player (19B, own penpal -- single slot, never REUSEPAL)
 *   -> enemy header (19B) -> enemy[0..GAME_MAX_ENEMIES-1] (11B each)
 *   -> boss (19B) -> power item (19B)
 *   -> player-bullet header (19B) ->
 *      pbullet[0..GAME_MAX_PLAYER_BULLETS-1] (11B each)
 *   -> enemy-bullet header (19B) ->
 *      ebullet[0..GAME_MAX_ENEMY_BULLETS-1] (11B each) -> next = NULL
 * A palette header SCB is only needed ahead of a *multi-slot* kind so a
 * SKIPped follower never leaves its group without a palette to REUSEPAL
 * from (scripts/verify-scb-skip-smoke-gearlynx.py, v044, confirmed SKIP
 * honored and header-latches-for-follower safe on gearlynx). The three
 * single-slot kinds (player/boss/power item) carry their own penpal and
 * may be freely SKIPped without a header. Every sprite belonging to one
 * kind shares one real-color penpal table (confirmed by
 * scripts/verify-phase-3r-sprite-bpp-gate.py together with the stage
 * roster: each stage's enemy_formation draws from exactly one of the
 * "enemy"/"mineral" sprite kinds, never both in the same frame), so the
 * enemy header's penpal/sprctl0 only need refreshing on stage change
 * (movable_scb_on_stage_change), not every frame.
 *
 * GAME_MAX_ENVIRONMENT_OBJECTS is 2 here (asteroids and falling rocks are
 * mutually exclusive per stage and share this env group), not the 4
 * v044's byte-budget comment assumed -- see .briefs/APS-053/v045.md for
 * the corrected count. Byte budget: 19 + 2*11 + 19 + 19 + 8*11 + 19 + 19
 * + 19 + 12*11 + 19 + 16*11 = 551B fixed static storage (vs. 529B for the
 * old dynamic pool; +22B net, not v044's estimated +44B, because of the
 * corrected env count). */
static const unsigned char movable_scb_empty_sprite[1] = { 0x00u };

/* APS-053 v046 test-only: movable_scb_empty_sprite is file-static, so it
 * has no exported debug symbol the gate(b) pixel-verification harness
 * can resolve from the .lbl file (cc65 does not export `static` symbols
 * to -Ln output) to distinguish a palette-only header SCB (data == this
 * address) from a real object SCB in the now-always-full static chain.
 * This non-static pointer exists purely for that; its value is a
 * link-time address constant. Not read by any production code path.
 * Always compiled in (not CADENCE_PROBE-only) since gate(b) runs against
 * the release ROM. */
const unsigned char* const movable_scb_empty_sprite_debug_export =
    movable_scb_empty_sprite;

/* v046 (see .briefs/APS-053/v046.md, Fable5 review): SCB_RENONE's
 * hpos/vpos are `signed int` (16-bit), but every movable object's
 * rect.x/rect.y is `unsigned char` (0..255, never negative), so the high
 * byte is always zero once written. cc65 compiles a plain `p->hpos =
 * (signed int)obj->rect.x` through a generic 16-bit runtime store helper
 * (staxspidx, ~55 cycles) that zero-extends and stores both bytes every
 * time. These macros instead store only the low byte (the struct's
 * static initializers already zero the high byte once, and it is never
 * written by anything else), which cc65 compiles to a single 8-bit
 * store. Little-endian assumption is safe: this is a 6502 target. */
#define MOVABLE_SET_HPOS(scb, value) \
    (((unsigned char*)&(scb)->hpos)[0] = (unsigned char)(value))
#define MOVABLE_SET_VPOS(scb, value) \
    (((unsigned char*)&(scb)->vpos)[0] = (unsigned char)(value))

/* v045 addendum (see .briefs/APS-053/v045.md, Fable5 design review): the
 * v044-shaped movable_scb_init that filled every field with sequential
 * runtime assignments compiled to ~1.1KB of CODE (41 slots x several
 * field writes each), blowing the RAM budget derived from a stale
 * baseline. Every one of those fields is a compile-time/link-time
 * constant (chain `next` pointers, sprctl0/1, sprcoll, fixed data/penpal
 * for the always-same-shape kinds), so this chain is instead built as
 * static initializers -- CODE cost zero, same DATA-segment storage a
 * runtime init would've needed. Declaration order is chain-tail-first
 * (ebullet -> ... -> env_header) so every `next` initializer only takes
 * the address of an object already fully declared above it: C allows an
 * initializer to take the address of any linkage-visible object, but not
 * to read another object's *value* at compile time, so only pointer
 * fields (next/data) and pure-constant fields can be filled this way --
 * enemy header's stage-dependent penpal/sprctl0 and player's
 * definition-derived penpal/sprctl0 still need the small runtime
 * fixup in movable_scb_init below (verified buildable: cc65 accepts
 * static initializers containing another static object's address either
 * direction, see the .briefs/APS-053/v045.md compile spike). */
static SCB_RENONE movable_scb_ebullet[GAME_MAX_ENEMY_BULLETS] = {
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[1], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[2], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[3], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[4], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[5], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[6], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[7], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[8], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[9], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[10], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[11], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[12], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[13], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[14], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet[15], (unsigned char*)enemy_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)0, (unsigned char*)enemy_bullet_shape, 0, 0 }
};

static SCB_RENONE_PAL movable_scb_ebullet_header = {
    (unsigned char)(BPP_1 | TYPE_NONCOLL), (unsigned char)(PACKED | RENONE),
    NO_COLLIDE, (char*)&movable_scb_ebullet[0],
    (unsigned char*)movable_scb_empty_sprite, 0, 0,
    { GAME_COLOR_ENEMY_BULLET, 0u, 0u, 0u, 0u, 0u, 0u, 0u }
};

static SCB_RENONE movable_scb_pbullet[GAME_MAX_PLAYER_BULLETS] = {
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[1], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[2], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[3], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[4], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[5], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[6], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[7], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[8], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[9], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[10], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_pbullet[11], (unsigned char*)player_bullet_shape,
      0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_ebullet_header, (unsigned char*)player_bullet_shape,
      0, 0 }
};

static SCB_RENONE_PAL movable_scb_pbullet_header = {
    (unsigned char)(BPP_1 | TYPE_NONCOLL), (unsigned char)(PACKED | RENONE),
    NO_COLLIDE, (char*)&movable_scb_pbullet[0],
    (unsigned char*)movable_scb_empty_sprite, 0, 0,
    { GAME_COLOR_BULLET, 0u, 0u, 0u, 0u, 0u, 0u, 0u }
};

static SCB_RENONE_PAL movable_scb_power_item = {
    (unsigned char)(BPP_1 | TYPE_NONCOLL),
    (unsigned char)(PACKED | RENONE | SKIP), NO_COLLIDE,
    (char*)&movable_scb_pbullet_header, (unsigned char*)power_item_shape,
    0, 0,
    { GAME_COLOR_POWER_ITEM, 0u, 0u, 0u, 0u, 0u, 0u, 0u }
};

/* Boss's sprctl0/penpal/data are appearance-dependent (resolved at
 * runtime by movable_scb_update_boss from the first active appearance),
 * so this initializer only fixes the fields that never change: sprcoll,
 * chain linkage, and an initially-SKIPped sprctl1. */
static SCB_RENONE_PAL movable_scb_boss = {
    0u, (unsigned char)(PACKED | RENONE | SKIP), NO_COLLIDE,
    (char*)&movable_scb_power_item, (unsigned char*)0, 0, 0,
    { 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u }
};

/* Enemy slots' sprctl0/data are sprite-kind-dependent (resolved at
 * runtime by movable_scb_update's per-slot cache), so only the
 * always-constant fields are initialized here. */
static SCB_RENONE movable_scb_enemy[GAME_MAX_ENEMIES] = {
    { 0u, (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_enemy[1], (unsigned char*)0, 0, 0 },
    { 0u, (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_enemy[2], (unsigned char*)0, 0, 0 },
    { 0u, (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_enemy[3], (unsigned char*)0, 0, 0 },
    { 0u, (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_enemy[4], (unsigned char*)0, 0, 0 },
    { 0u, (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_enemy[5], (unsigned char*)0, 0, 0 },
    { 0u, (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_enemy[6], (unsigned char*)0, 0, 0 },
    { 0u, (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_enemy[7], (unsigned char*)0, 0, 0 },
    { 0u, (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_boss, (unsigned char*)0, 0, 0 }
};

/* Enemy header's sprctl0/penpal are stage-dependent (filled by
 * movable_scb_on_stage_change on the first update); this default just
 * keeps the header a valid, harmless (0-pixel, black) SCB before that
 * runs. */
static SCB_RENONE_PAL movable_scb_enemy_header = {
    (unsigned char)(BPP_1 | TYPE_NONCOLL), (unsigned char)(PACKED | RENONE),
    NO_COLLIDE, (char*)&movable_scb_enemy[0],
    (unsigned char*)movable_scb_empty_sprite, 0, 0,
    { 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u }
};

/* Player's sprctl0/penpal come from GAME_SPRITE_PLAYER's
 * GameSpriteDefinition (an extern const array element -- its *value*
 * isn't a compile-time constant expression, only its address is), so
 * they're filled by the small runtime fixup in movable_scb_init. */
static SCB_RENONE_PAL movable_scb_player = {
    0u, (unsigned char)(PACKED | RENONE | SKIP), NO_COLLIDE,
    (char*)&movable_scb_enemy_header, (unsigned char*)0, 0, 0,
    { 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u }
};

static SCB_RENONE movable_scb_env[GAME_MAX_ENVIRONMENT_OBJECTS] = {
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_env[1], (unsigned char*)0, 0, 0 },
    { (unsigned char)(BPP_1 | TYPE_NONCOLL),
      (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP), NO_COLLIDE,
      (char*)&movable_scb_player, (unsigned char*)0, 0, 0 }
};

static SCB_RENONE_PAL movable_scb_env_header = {
    (unsigned char)(BPP_1 | TYPE_NONCOLL), (unsigned char)(PACKED | RENONE),
    NO_COLLIDE, (char*)&movable_scb_env[0],
    (unsigned char*)movable_scb_empty_sprite, 0, 0,
    { GAME_COLOR_ENVIRONMENT_BODY, 0u, 0u, 0u, 0u, 0u, 0u, 0u }
};

#ifdef CADENCE_PROBE
/* APS-053 v045 test-only: movable_scb_env_header is file-static, so it
 * has no exported debug symbol the gate(a) breakdown harness can resolve
 * from the .lbl file (cc65 does not export `static` symbols to -Ln
 * output). This non-static pointer exists purely so the harness can
 * resolve the static chain's head address; its own address is a
 * link-time constant (movable_scb_env_header is already fully declared
 * above), so no runtime assignment is needed. Not read by any
 * production code path. */
void* scb_split_probe_chain_head = &movable_scb_env_header;
#endif

/* Per-slot cache for the two "sprite kind" groups (enemy/boss): avoids
 * re-deriving frame pointers/anchor from game_sprite_definitions every
 * frame when a slot keeps drawing the same sprite id, which is the
 * common case. This is v044's original 7B shape (sprite_id + both frame
 * pointers + dx/dy), restored per Fable5's v045 review after the actual
 * RAM shortfall was traced to movable_scb_init's CODE size, not this
 * cache's DATA size -- the 3B compressed shape (sprite_id + definition
 * pointer only) traded ~40B of DATA for ~150-200B of CODE and slower
 * per-frame re-derivation, which is a bad trade once init is free.
 * [0..GAME_MAX_ENEMIES-1] = enemy slots, [GAME_MAX_ENEMIES] = boss.
 * GAME_SPRITE_INVALID (0xFF) is not a valid game_sprite_definitions
 * index, so every slot starts as a guaranteed cache miss. */
typedef struct MovableSpriteCache {
    unsigned char sprite_id;
    const unsigned char* frame0_ptr;
    const unsigned char* frame1_ptr;
    signed char dx;
    signed char dy;
} MovableSpriteCache;
static MovableSpriteCache movable_sprite_cache[GAME_MAX_ENEMIES + 1u] = {
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 },
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 },
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 },
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 },
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 },
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 },
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 },
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 },
    { GAME_SPRITE_INVALID, (const unsigned char*)0, (const unsigned char*)0,
      0, 0 }
};
#define MOVABLE_BOSS_CACHE_SLOT GAME_MAX_ENEMIES

/* Player's sprite id is fixed for the whole run (GAME_SPRITE_PLAYER), so
 * its definition pointer is a compile-time address constant. */
static const GameSpriteDefinition* movable_scb_player_def =
    &game_sprite_definitions[GAME_SPRITE_PLAYER];

/* Cache key for movable_scb_on_stage_change: the enemy header's
 * penpal/sprctl0 only need refreshing when the stage's enemy roster
 * (and therefore its shared sprite kind) changes, not every frame. 0xFF
 * never matches a real GameStageConfig.enemy_formation_id, forcing a
 * refresh on the first update. */
static unsigned char movable_scb_enemy_formation_id = 0xFFu;

#ifdef CADENCE_PROBE
/* APS-053 v040 test-only: with movable_scb_* now file-static named
 * structs (no single contiguous pool any more), the gate(a) breakdown
 * harness resolves timing landmarks from scb_split_marker_begin/
 * finish_enter/finish_exit only; it no longer reads back pool contents
 * through an exported pointer. See .briefs/APS-053/v045.md "existing
 * assets" and the corresponding harness update in
 * scripts/verify-phase-3r-gate-a-breakdown-gearlynx.py. */
#endif

/* Only the two fields that depend on an extern const array *value*
 * (not just its address, which the static initializers above already
 * captured) -- GAME_SPRITE_PLAYER's own sprctl0/penpal -- need a runtime
 * fixup; everything else about the chain is link-time constant. */
static void movable_scb_init(void)
{
    movable_scb_player.sprctl0 = movable_scb_player_def->sprctl0;
    movable_scb_player.penpal[0] = movable_scb_player_def->penpal[0];
    movable_scb_player.penpal[1] = movable_scb_player_def->penpal[1];
    movable_scb_player.penpal[2] = movable_scb_player_def->penpal[2];
}

/* Refreshes the enemy palette header only when the stage's enemy roster
 * changes (verify-phase-3r-sprite-bpp-gate.py-confirmed: every stage's
 * roster shares one sprite kind, so slot 0 of the formation is a safe
 * representative for the whole stage). */
static void movable_scb_on_stage_change(const GameStageConfig* stage_config)
{
    const GameEnemyFormationSlot* slot0;
    unsigned char sprite_id;
    const GameSpriteDefinition* def;

    if (movable_scb_enemy_formation_id == stage_config->enemy_formation_id) {
        return;
    }
    movable_scb_enemy_formation_id = stage_config->enemy_formation_id;
    slot0 = game_get_enemy_formation_slot(stage_config->enemy_formation_id,
        0u);
    if (slot0 == (const GameEnemyFormationSlot*)0) {
        return;
    }
    sprite_id = game_enemy_sprite_ids[slot0->type];
    if (sprite_id >= GAME_SPRITE_COUNT) {
        return;
    }
    def = &game_sprite_definitions[sprite_id];
    movable_scb_enemy_header.sprctl0 = def->sprctl0;
    movable_scb_enemy_header.penpal[0] = def->penpal[0];
    movable_scb_enemy_header.penpal[1] = def->penpal[1];
    movable_scb_enemy_header.penpal[2] = def->penpal[2];
}

static void movable_scb_update_boss(const GameState* game,
    unsigned char frame)
{
    const GameBoss* boss = &game->boss;
    unsigned char sprite_id;
    MovableSpriteCache* cache;

    /* Caller (movable_scb_update) only reaches this function when
     * game->phase != GAME_PHASE_ALL_CLEAR, so that check is not repeated
     * here (see .briefs/APS-053/v046.md Fable5 finding: re-evaluating a
     * loop-invariant condition every call/iteration was a measured
     * cost). */
    if (boss->active == 0u ||
        boss->appearance_id >= GAME_BOSS_APPEARANCE_COUNT) {
        movable_scb_boss.sprctl1 = (unsigned char)(PACKED | RENONE | SKIP);
        return;
    }
    sprite_id = game_boss_sprite_ids[boss->appearance_id];
    if (sprite_id == GAME_SPRITE_INVALID) {
        movable_scb_boss.sprctl1 = (unsigned char)(PACKED | RENONE | SKIP);
        return;
    }
    cache = &movable_sprite_cache[MOVABLE_BOSS_CACHE_SLOT];
    if (cache->sprite_id != sprite_id) {
        const GameSpriteDefinition* def = &game_sprite_definitions[sprite_id];

        cache->sprite_id = sprite_id;
        cache->frame0_ptr = game_sprite_packed_data + def->frame0_offset;
        cache->frame1_ptr = game_sprite_packed_data + def->frame1_offset;
        cache->dx = (signed char)((def->anchor >> 4) & 0x0Fu) - 8;
        cache->dy = (signed char)(def->anchor & 0x0Fu) - 8;
        movable_scb_boss.sprctl0 = def->sprctl0;
        movable_scb_boss.penpal[0] = def->penpal[0];
        movable_scb_boss.penpal[1] = def->penpal[1];
        movable_scb_boss.penpal[2] = def->penpal[2];
    }
    movable_scb_boss.sprctl1 = (unsigned char)(PACKED | RENONE);
    movable_scb_boss.data = (unsigned char*)(frame != 0u ? cache->frame1_ptr :
        cache->frame0_ptr);
    movable_scb_boss.hpos = (signed int)(boss->rect.x + cache->dx);
    movable_scb_boss.vpos = (signed int)(boss->rect.y + cache->dy);
}

/* Per-frame differential update: walks each kind's static slots with a
 * pointer (cc65 generates tighter code for pointer walks than indexed
 * array access) and only ever writes SPRCTL1 (SKIP bit)/hpos/vpos/data
 * (animated kinds only) -- see .briefs/APS-053/v044.md "frame-by-frame
 * differential update". Death/liveness conditions are a verbatim mirror
 * of the pre-v045 append conditions (draw_environment/draw_game). The
 * chain is always submitted in full, including an ALL_CLEAR frame where
 * every slot is SKIPped: the four always-present palette headers still
 * draw (0 pixels each), which is the intentionally cheap fallback v044
 * chose over conditionally omitting the whole submit. */
static void movable_scb_update(const GameState* game,
    const GameStageConfig* stage_config)
{
    unsigned char i;
    unsigned char frame;
    unsigned char all_clear;
#ifdef APS056_DIAGNOSTIC
    unsigned char diagnostic_active_count;
#endif
    SCB_RENONE* p;

#ifdef CADENCE_PROBE
    scb_split_marker_begin();
#endif
    frame = game->animation_frame;
    all_clear = (unsigned char)(game->phase == GAME_PHASE_ALL_CLEAR);
#ifdef APS056_DIAGNOSTIC
    diagnostic_active_count = 0u;
#endif
    movable_scb_on_stage_change(stage_config);
#ifdef APS056_DIAGNOSTIC
    movable_scb_ebullet_header.penpal[0] = (game->diagnostic_controls &
        GAME_DIAGNOSTIC_CONTROL_BULLET_WHITE) != 0u ?
        GAME_COLOR_WHITE : GAME_COLOR_ENEMY_BULLET;
#endif

    /* --- environment hazards: asteroids/falling rocks are mutually
     * exclusive per stage (GameStageConfig.environment_id) and share this
     * env group; wind stages don't use SCB movable objects at all (see
     * draw_wind_band, still TGI). game->phase is only tested once here
     * (branch, not per-slot), and each object array is walked by pointer
     * instead of `game->asteroids[i]`-style indexing. */
    if (game->phase == GAME_PHASE_NORMAL &&
        stage_config->environment_id == GAME_ENVIRONMENT_ASTEROIDS) {
        const GameAsteroid* obj = game->asteroids;

        p = movable_scb_env;
        for (i = 0u; i < GAME_MAX_ENVIRONMENT_OBJECTS; ++i, ++p, ++obj) {
            if (obj->active != 0u) {
                p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL);
                p->data = (unsigned char*)asteroid_shapes[frame];
                MOVABLE_SET_HPOS(p, obj->rect.x);
                MOVABLE_SET_VPOS(p, obj->rect.y);
            } else {
                p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL |
                    SKIP);
            }
        }
    } else if (game->phase == GAME_PHASE_NORMAL &&
        stage_config->environment_id != GAME_ENVIRONMENT_WIND) {
        const GameFallingRock* obj = game->falling_rocks;

        p = movable_scb_env;
        for (i = 0u; i < GAME_MAX_ENVIRONMENT_OBJECTS; ++i, ++p, ++obj) {
            if (obj->state == GAME_ROCK_STATE_FALLING) {
                p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL);
                p->data = (unsigned char*)falling_rock_shapes[frame];
                MOVABLE_SET_HPOS(p, obj->rect.x);
                MOVABLE_SET_VPOS(p, obj->rect.y);
            } else {
                p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL |
                    SKIP);
            }
        }
    } else {
        p = movable_scb_env;
        for (i = 0u; i < GAME_MAX_ENVIRONMENT_OBJECTS; ++i, ++p) {
            p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP);
        }
    }

    /* v046 (see .briefs/APS-053/v046.md, Fable5 review): re-evaluating
     * `game->phase != GAME_PHASE_ALL_CLEAR` every loop iteration below
     * (41 slots across player/enemy/boss/power_item/pbullet/ebullet) cost
     * ~48 cycles/iteration in the generated code -- game->phase is
     * loop-invariant, so it is tested once here instead and the two
     * outcomes are two separate, unconditioned code paths. */
    if (all_clear != 0u) {
        movable_scb_player.sprctl1 = (unsigned char)(PACKED | RENONE | SKIP);
        p = movable_scb_enemy;
        for (i = 0u; i < GAME_MAX_ENEMIES; ++i, ++p) {
            p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP);
        }
        movable_scb_boss.sprctl1 = (unsigned char)(PACKED | RENONE | SKIP);
        movable_scb_power_item.sprctl1 =
            (unsigned char)(PACKED | RENONE | SKIP);
        p = movable_scb_pbullet;
        for (i = 0u; i < GAME_MAX_PLAYER_BULLETS; ++i, ++p) {
            p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP);
        }
        p = movable_scb_ebullet;
        for (i = 0u; i < GAME_MAX_ENEMY_BULLETS; ++i, ++p) {
            p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL | SKIP);
        }
#ifdef APS056_DIAGNOSTIC
        aps056_active_bullet_count = 0u;
#endif
    } else {
        /* --- player --- */
        if (game->dying == 0u && game_player_is_visible(game) != 0u) {
            movable_scb_player.sprctl1 = (unsigned char)(PACKED | RENONE);
            movable_scb_player.data =
                (unsigned char*)(game_sprite_packed_data +
                (frame != 0u ? movable_scb_player_def->frame1_offset :
                    movable_scb_player_def->frame0_offset));
            movable_scb_player.hpos = (signed int)(game->player.x +
                ((signed char)((movable_scb_player_def->anchor >> 4) &
                    0x0Fu) - 8));
            movable_scb_player.vpos = (signed int)(game->player.y +
                ((signed char)(movable_scb_player_def->anchor & 0x0Fu) -
                    8));
        } else {
            movable_scb_player.sprctl1 =
                (unsigned char)(PACKED | RENONE | SKIP);
        }

        /* --- enemies (sprite kind, per-slot cache, pointer walk instead
         * of game_enemy_at(game, i)'s repeated game->enemies reload) --- */
        {
            const GameEnemy* enemy = game->enemies;

            p = movable_scb_enemy;
            for (i = 0u; i < GAME_MAX_ENEMIES; ++i, ++p, ++enemy) {
                MovableSpriteCache* cache = &movable_sprite_cache[i];
                unsigned char sprite_id;

                if (enemy->active == 0u ||
                    enemy->rect.x >= GAME_SCREEN_WIDTH) {
                    p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL |
                        SKIP);
                    continue;
                }
                sprite_id = game_enemy_sprite_ids[enemy->type];
                if (cache->sprite_id != sprite_id) {
                    const GameSpriteDefinition* def =
                        &game_sprite_definitions[sprite_id];

                    cache->sprite_id = sprite_id;
                    cache->frame0_ptr =
                        game_sprite_packed_data + def->frame0_offset;
                    cache->frame1_ptr =
                        game_sprite_packed_data + def->frame1_offset;
                    cache->dx =
                        (signed char)((def->anchor >> 4) & 0x0Fu) - 8;
                    cache->dy = (signed char)(def->anchor & 0x0Fu) - 8;
                    p->sprctl0 = def->sprctl0;
                }
                p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL);
                p->data = (unsigned char*)(frame != 0u ? cache->frame1_ptr :
                    cache->frame0_ptr);
                p->hpos = (signed int)(enemy->rect.x + cache->dx);
                p->vpos = (signed int)(enemy->rect.y + cache->dy);
            }
        }

        /* --- boss (game->phase != ALL_CLEAR already established) --- */
        movable_scb_update_boss(game, frame);

        /* --- power item --- */
        if (game->power_item.active != 0u) {
            movable_scb_power_item.sprctl1 =
                (unsigned char)(PACKED | RENONE);
            movable_scb_power_item.hpos =
                (signed int)game->power_item.rect.x;
            movable_scb_power_item.vpos =
                (signed int)game->power_item.rect.y;
        } else {
            movable_scb_power_item.sprctl1 =
                (unsigned char)(PACKED | RENONE | SKIP);
        }

        /* --- player bullets (pointer walk) --- */
        {
            const GameBullet* bullet = game->bullets;

            p = movable_scb_pbullet;
            for (i = 0u; i < GAME_MAX_PLAYER_BULLETS; ++i, ++p, ++bullet) {
                if (bullet->active != 0u) {
                    p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL);
                    MOVABLE_SET_HPOS(p, bullet->rect.x);
                    MOVABLE_SET_VPOS(p, bullet->rect.y);
                } else {
                    p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL |
                        SKIP);
                }
            }
        }

        /* --- enemy bullets (pointer walk) --- */
        {
            const GameEnemyBullet* ebullet = game->enemy_bullets;

            p = movable_scb_ebullet;
            for (i = 0u; i < GAME_MAX_ENEMY_BULLETS; ++i, ++p, ++ebullet) {
#ifdef APS056_DIAGNOSTIC
                if (ebullet->active != 0u) {
                    ++diagnostic_active_count;
                }
#endif
                if (ebullet->active != 0u &&
                    ebullet->rect.y >= GAME_HUD_HEIGHT) {
                    p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL);
                    MOVABLE_SET_HPOS(p, ebullet->rect.x);
                    MOVABLE_SET_VPOS(p, ebullet->rect.y);
                } else {
                    p->sprctl1 = (unsigned char)(PACKED | RENONE | REUSEPAL |
                        SKIP);
                }
            }
#ifdef APS056_DIAGNOSTIC
            aps056_active_bullet_count = diagnostic_active_count;
#endif
        }
    }

#ifdef CADENCE_PROBE
    scb_split_marker_finish_enter();
#endif
    tgi_sprite((char*)&movable_scb_env_header);
#ifdef CADENCE_PROBE
    scb_split_marker_finish_exit();
#endif
}

static void draw_phase_overlay(const GameState* game)
{
    if (game->phase == GAME_PHASE_WARNING) {
        static_layer_text(52, 45, "WARNING", GAME_COLOR_WHITE);
    } else if (game->phase == GAME_PHASE_STAGE_CLEAR) {
        static_layer_text(36, 45, "STAGE CLEAR", GAME_COLOR_WHITE);
    } else if (game->phase == GAME_PHASE_ALL_CLEAR) {
        static_layer_text(44, 40, "ALL CLEAR", GAME_COLOR_WHITE);
        static_layer_text(36, 58, "A/B TO RESTART", GAME_COLOR_WHITE);
    }
}

static void draw_wind_band(const GameWindBand* wind)
{
    unsigned char x;
    unsigned char y;
    unsigned char bottom;

    bottom = (unsigned char)(wind->y + GAME_WIND_BAND_HEIGHT - 1u);
    if (wind->state == GAME_WIND_STATE_WARNING) {
        tgi_setcolor(GAME_COLOR_WIND_WARNING);
        for (x = 0u; x < GAME_SCREEN_WIDTH; x = (unsigned char)(x + 12u)) {
            unsigned int x1;

            x1 = (unsigned int)x + 4u;
            if (x1 >= GAME_SCREEN_WIDTH) {
                x1 = GAME_SCREEN_WIDTH - 1u;
            }
            tgi_bar(x, wind->y, x1, wind->y);
            tgi_bar(x, bottom, x1, bottom);
        }
    } else {
        tgi_setcolor(GAME_COLOR_WIND_ACTIVE);
        for (y = (unsigned char)(wind->y + 5u); y < bottom;
            y = (unsigned char)(y + 7u)) {
            tgi_line(8u, y, 151u, y);
        }
    }
    for (x = 20u; x < GAME_SCREEN_WIDTH; x = (unsigned char)(x + 40u)) {
        unsigned char center_y;

        center_y = (unsigned char)(wind->y + GAME_WIND_BAND_HEIGHT / 2u);
        if (wind->direction == GAME_WIND_DIRECTION_UP) {
            tgi_line(x, (unsigned int)center_y + 4u, x, center_y - 4u);
            tgi_line(x, center_y - 4u, x - 2u, center_y - 1u);
            tgi_line(x, center_y - 4u, x + 2u, center_y - 1u);
        } else {
            tgi_line(x, center_y - 4u, x, (unsigned int)center_y + 4u);
            tgi_line(x, (unsigned int)center_y + 4u,
                x - 2u, (unsigned int)center_y + 1u);
            tgi_line(x, (unsigned int)center_y + 4u,
                x + 2u, (unsigned int)center_y + 1u);
        }
    }
}

/* TGI-only overlays for the environment hazards: the asteroid/falling-rock
 * bodies themselves are now part of the static movable SCB chain
 * (movable_scb_update's env group), so this function only draws what was
 * never SCB-eligible -- the falling-rock warning/impact TGI runs and the
 * wind band (never converted, see draw_wind_band). */
static void draw_environment(const GameState* game,
    const GameStageConfig* stage_config)
{
    unsigned char i;

    if (game->phase != GAME_PHASE_NORMAL) {
        return;
    }
    if (stage_config->environment_id == GAME_ENVIRONMENT_ASTEROIDS) {
        return;
    }
    if (stage_config->environment_id == GAME_ENVIRONMENT_WIND) {
        if (game->wind.state != GAME_WIND_STATE_INACTIVE) {
            draw_wind_band(&game->wind);
        }
        return;
    }
    for (i = 0u; i < GAME_MAX_ENVIRONMENT_OBJECTS; ++i) {
        const GameFallingRock* rock;
        unsigned char y;

        rock = &game->falling_rocks[i];
        if (rock->state == GAME_ROCK_STATE_WARNING) {
            tgi_setcolor(GAME_COLOR_WIND_ACTIVE);
            for (y = 14u; y < 91u; y = (unsigned char)(y + 12u)) {
                tgi_bar(rock->rect.x + 3u, y,
                    rock->rect.x + 4u, y + 2u);
            }
            tgi_line(rock->rect.x, 94u,
                rock->rect.x + GAME_ENVIRONMENT_OBJECT_WIDTH - 1u, 94u);
            tgi_line(rock->rect.x, 94u, rock->rect.x + 2u, 91u);
            tgi_line(rock->rect.x + 7u, 94u,
                rock->rect.x + 5u, 91u);
        } else if (rock->state == GAME_ROCK_STATE_IMPACT) {
            tgi_setcolor(GAME_COLOR_ENVIRONMENT_DETAIL);
            tgi_line(rock->rect.x, 98u, rock->rect.x + 7u, 98u);
            tgi_line(rock->rect.x + 2u, 96u,
                rock->rect.x + 5u, 96u);
        }
    }
}

/* The stock TGI font is ASCII-only. Keep the exact project credit visible by
 * drawing "VOICEVOX:Nemo" with that font and the required full-width
 * Japanese suffix as compact 5x7 glyphs. The row at y=82 sits below the
 * controls and above the version without overlap on the 160x102 display. */
static void draw_voice_credit(void)
{
    static_layer_title_text(VOICE_CREDIT_ASCII_X, VOICE_CREDIT_Y, 4u,
        GAME_COLOR_WHITE);
    static_layer_credit_suffix(VOICE_CREDIT_SUFFIX_X, VOICE_CREDIT_Y,
        GAME_COLOR_WHITE);
}

static void draw_game(const GameState* game)
{
    const GameStageConfig* stage_config;

    if (game->phase == GAME_PHASE_TITLE) {
        static_layer_draw(0, GAME_BACKGROUND_THEME_SPACE);
        static_layer_title_text(24, 18, 0u, GAME_COLOR_WHITE);
        static_layer_title_text(32, 42, 1u, GAME_COLOR_WHITE);
        static_layer_title_text(28, 62, 2u, GAME_COLOR_WHITE);
        static_layer_title_text(36, 74, 3u, GAME_COLOR_WHITE);
        draw_voice_credit();
        static_layer_text(52, 90, "V" GAME_VERSION_STRING, GAME_COLOR_WHITE);
        game_display_request();
        return;
    }

    stage_config = game_get_stage_config(game->stage);
    if (active_palette_stage != game->stage) {
        tgi_setpalette(game_stage_palettes[game->stage - 1u]);
        active_palette_stage = game->stage;
    }
#if defined(CADENCE_PROBE) && defined(CADENCE_VARIANT)
#if CADENCE_VARIANT == 3
    game_display_request();
    return;
#elif CADENCE_VARIANT == 2
    if (game->phase != GAME_PHASE_ALL_CLEAR &&
        game->dying == 0u && game_player_is_visible(game) != 0u) {
        draw_sprite(game->player.x, game->player.y,
            GAME_SPRITE_PLAYER, game->animation_frame);
    }
    game_display_request();
    return;
#elif CADENCE_VARIANT == 1
    static_layer_draw(game, stage_config->background_theme_id);
    game_display_request();
    return;
#endif
#endif
    static_layer_draw(game, stage_config->background_theme_id);
    tgi_setcolor(GAME_COLOR_WHITE);
    draw_phase_overlay(game);
    draw_environment(game, stage_config);
    if (game->phase != GAME_PHASE_ALL_CLEAR && game->dying != 0u) {
        draw_mask((int)game->player.x,
            (int)game->player.y - 1, 8u, 8u,
            explosion_masks[game->explosion_timer /
                GAME_EXPLOSION_STAGE_FRAMES],
            GAME_COLOR_EXPLOSION);
    }
    movable_scb_update(game, stage_config);
    if (game->game_over != 0u) {
        static_layer_text(48, 40, "GAME OVER", GAME_COLOR_WHITE);
        if (game->game_over_voice_complete != 0u) {
            static_layer_text(40, 58, "A/B TO TITLE", GAME_COLOR_WHITE);
        } else {
            static_layer_text(48, 58, "VOICE...", GAME_COLOR_WHITE);
        }
    }
    game_display_request();
}

void game_display_request(void)
{
    static_layer_text_flush();
#ifdef CADENCE_PROBE
    cadence_probe_hold_fixture();
    cadence_probe_capture_state();
    cadence_probe_display();
#endif
    tgi_updatedisplay();
}

void game_display_sync_complete(void)
{
}

void main(void)
{
    unsigned int elapsed_vblanks;
    unsigned char logic_updates;
    register unsigned int sound_ticks;
    unsigned char input;

    tgi_install(tgi_static_stddrv);
    tgi_init();
    joy_install(joy_static_stddrv);
    CLI();
    while (tgi_busy() != 0u) {
    }
    tgi_setbgcolor(GAME_COLOR_BLACK);
    tgi_setframerate(75u);
    sound_backend_init();
    title_voice_init();
    game_timing_init();
    game.enemies = game_enemies;
    game_init(&game);
    active_palette_stage = 0u;
    movable_scb_init();
    for (;;) {
        /* Pipeline gameplay work while the previous VBLANK swap is pending.
         * Only wait immediately before reusing the completed back buffer. */
        input = game_input_poll();
        elapsed_vblanks = game_timing_consume_vblanks();
#ifdef CADENCE_PROBE
        cadence_probe_elapsed_vblanks(elapsed_vblanks);
#endif
        logic_updates = game_logic_updates_for_draw_frame(elapsed_vblanks,
            0);
#ifdef APS056_DIAGNOSTIC
        if (logic_updates == 0u) {
            game_diagnostic_update_controls(&game, input);
        }
#endif
        while (logic_updates != 0u) {
#ifdef CADENCE_PROBE
            cadence_probe_hold_fixture();
#endif
            game_update_logic(&game, input);
#ifdef CADENCE_PROBE
            /* Count only after the real game update returns. */
            cadence_probe_logic_update();
#endif
            --logic_updates;
        }
#ifdef CADENCE_PROBE
#endif
        sound_ticks = game_sound_ticks_for_draw_frame(elapsed_vblanks);
        while (sound_ticks != 0u) {
            game_sound_tick(&game);
#ifdef CADENCE_PROBE
            /* Count only after the real production sound tick returns. */
            cadence_probe_sound_tick();
#endif
            --sound_ticks;
        }
        sound_backend_apply_all();
        GAME_DISPLAY_READY_WAIT(tgi_busy());
        game_display_sync_complete();
        draw_game(&game);
        if (game.phase == GAME_PHASE_TITLE &&
            game.title_voice_pending == GAME_TITLE_VOICE_PENDING) {
            if (title_voice_start() != 0u) {
                while (title_voice_is_playing() != 0u) {
                    title_voice_pump();
                }
                title_voice_stop();
            }
            game_title_voice_complete(&game);
            game_timing_reset_baseline();
        } else if (game.game_over != 0u &&
            game.game_over_voice_pending != 0u) {
            if (game_over_voice_start() != 0u) {
                while (title_voice_is_playing() != 0u) {
                    title_voice_pump();
                }
                title_voice_stop();
            }
            game_game_over_voice_complete(&game);
            game_timing_reset_baseline();
        }
    }
}
