;
; Cartridge-only overlay payloads for scene-exclusive static layer data
; (APS-053 T2, docs/plan/2026-08-17-ram-reclamation.md). Same pattern as
; src/title_voice_asset.s: kept out of resident MAIN RODATA, exposed as Lynx
; directory entries 3-6 (see src/cart_directory.s). Binaries are generated by
; scripts/generate-static-layer.py; do not edit by hand.
;

        .segment        "OVERLAYSTAGE1"
        .incbin         "assets/overlay/stage1.bin"

        .segment        "OVERLAYSTAGE2"
        .incbin         "assets/overlay/stage2.bin"

        .segment        "OVERLAYSTAGE3"
        .incbin         "assets/overlay/stage3.bin"

        .segment        "OVERLAYTITLE"
        .incbin         "assets/overlay/title.bin"
